# Generated by Django 5.0.6 on 2024-07-05 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECC', '0003_product_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_genero',
        ),
        migrations.RemoveField(
            model_name='order',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
